version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: socket.io
    versions:
    - "> 1.4.8"
  - dependency-name: socket.io-client
    versions:
    - "> 1.7.4"
  - dependency-name: socket.io-stream
    versions:
    - "> 0.6.1"
  - dependency-name: tail
    versions:
    - "> 0.4.0"
  - dependency-name: redis
    versions:
    - 3.1.0
    - 3.1.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: underscore
    versions:
    - 1.12.0
    - 1.12.1
    - 1.13.0
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
