name: dispatch receiver

on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: alialaa/issue-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Bump HyPhy Release
        body: HyPhy release needs bumped
    - name: dispatch trigger
      if: github.event.action == "hyphy_release"
      run: |
        echo 'Created new issue'
